### ISSUE TITLE
Windows, MacOS compatability

### ISSUE THREAD

**Issue by stubbulon5** [ika-musuko/openFrameworks-clion#1]
Hello there my friend. Does this project template work only on Linux ?

**Comment by ika-musuko** [comment]
i only tested it on linux. 

i feel like getting it to work on mac might not be too much trouble since mac and linux are similar (i'm going to assume you know how to use brew or whatever package manager you use on mac) but i am very uncertain about this working on windows (nor do i know how to do so)

if there is demand i will consider trying windows myself (sounds painful!!!) however i don't have access to a mac. 

you can try setting this up on whichever OS regardless and if you have issues, please make another issue thread.

**Comment by ika-musuko** [comment]
https://github.com/neoxharsh/openFrameworks-Clion-Windows

apparently this guy is doing windows support so you can check out his project for that

**Comment by stubbulon5** [comment]
Thanks for sharing. Really appreciate it. G/L with your endeavours!

**Comment by ika-musuko** [comment]
closing for now, if anyone has a specific problem with an OS, make a new thread and tell me specifically what went wrong and what you did there
