### ISSUE TITLE
GST error

### ISSUE THREAD

**Issue by davidgodzsak** [ika-musuko/openFrameworks-clion#2]
After following the steps to set up, and also running apt-get install gstreamer* I still get the error `fatal error: gst/gst.h: No such file or directory.`. I have tried anything. If I build with the Makefile, and then run it by hand it works just fine, but with CMake test it does not. I am a bit lost on this, any ideas? I suspect the FindGStreamer.cmake does not work correctly. I also get this error with apt-get install gstreamer* 
```
The following packages have unmet dependencies:
 gstreamer1.0-python3-dbg-plugin-loader : Conflicts: gstreamer1.0-python3-plugin-loader but 1.14.1-1~ubuntu18.04.1 is to be installed
 gstreamer1.0-python3-plugin-loader : Conflicts: gstreamer1.0-python3-dbg-plugin-loader but 1.14.1-1~ubuntu18.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by ika-musuko** [comment]
are you building using the oFDebug build configuration I provided? 

this setup doesn't use cmake to build (mainly because i haven't figured it out lol), it only uses cmake so you can get proper syntax highlighting and jetbrains code suggestions. so don't use the default one clion gives you. 

with my oFDebug build configuration, this should work pretty seamlessly and you can even use clion's built in debugger.

**Comment by ika-musuko** [comment]
regarding your gstreamer install failing, you can probably try http://www.iasptk.com/ubuntu-fix-broken-package-best-solution/

**Comment by ika-musuko** [comment]
no replies on this in over a year, closing for now

**Comment by shortwavedave** [comment]
If anyone runs across this, the problem for me was that the ofDebug configuration had an extra step (in the "Before launch" section) that ran cmake first. If you remove that step then this works well
